/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBossQuestionRouteImport } from './routes/_authenticated/boss-question'
import { Route as AuthenticatedDailyDoubleRouteImport } from './routes/_authenticated/daily-double'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedVocabBingoRouteImport } from './routes/_authenticated/vocab-bingo'
import { Route as AuthenticatedWagerRoundRouteImport } from './routes/_authenticated/wager-round'
import { Route as AuthenticatedAssignmentsAssignmentIdRouteImport } from './routes/_authenticated/assignments.$assignmentId'
import { Route as AuthenticatedChallengeMatchIdRouteImport } from './routes/_authenticated/challenge.$matchId'
import { Route as AuthenticatedPresentCodeRouteImport } from './routes/_authenticated/present.$code'
import { Route as AuthenticatedQuizQuizIdRouteImport } from './routes/_authenticated/quiz.$quizId'
import { Route as OauthGoogleDriveReturnRouteImport } from './routes/oauth/google-drive.return'
import { Route as AuthenticatedAssignmentsAssignmentIdIndexRouteImport } from './routes/_authenticated/assignments.$assignmentId.index'
import { Route as AuthenticatedAssignmentsAssignmentIdPreviewRouteImport } from './routes/_authenticated/assignments.$assignmentId.preview'
import { Route as AuthenticatedClassesClassIdIndexRouteImport } from './routes/_authenticated/classes.$classId.index'
import { Route as AuthenticatedClassesClassIdGamesRouteImport } from './routes/_authenticated/classes.$classId.games'
import { Route as AuthenticatedClassesClassIdHomeworkRouteImport } from './routes/_authenticated/classes.$classId.homework'
import { Route as AuthenticatedClassesClassIdMaterialsRouteImport } from './routes/_authenticated/classes.$classId.materials'
import { Route as AuthenticatedClassesClassIdQuizzesRouteImport } from './routes/_authenticated/classes.$classId.quizzes'
import { Route as AuthenticatedSubmissionsAssignmentIdStudentIdRouteImport } from './routes/_authenticated/submissions.$assignmentId.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBossQuestionRoute =
  AuthenticatedBossQuestionRouteImport.update({
    id: '/boss-question',
    path: '/boss-question',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDailyDoubleRoute =
  AuthenticatedDailyDoubleRouteImport.update({
    id: '/daily-double',
    path: '/daily-double',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVocabBingoRoute = AuthenticatedVocabBingoRouteImport.update({
  id: '/vocab-bingo',
  path: '/vocab-bingo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWagerRoundRoute = AuthenticatedWagerRoundRouteImport.update({
  id: '/wager-round',
  path: '/wager-round',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssignmentsAssignmentIdRoute =
  AuthenticatedAssignmentsAssignmentIdRouteImport.update({
    id: '/assignments/$assignmentId',
    path: '/assignments/$assignmentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChallengeMatchIdRoute =
  AuthenticatedChallengeMatchIdRouteImport.update({
    id: '/challenge/$matchId',
    path: '/challenge/$matchId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPresentCodeRoute =
  AuthenticatedPresentCodeRouteImport.update({
    id: '/present/$code',
    path: '/present/$code',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuizQuizIdRoute = AuthenticatedQuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const OauthGoogleDriveReturnRoute = OauthGoogleDriveReturnRouteImport.update({
  id: '/oauth/google-drive/return',
  path: '/oauth/google-drive/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssignmentsAssignmentIdIndexRoute =
  AuthenticatedAssignmentsAssignmentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAssignmentsAssignmentIdRoute,
  } as any)
const AuthenticatedAssignmentsAssignmentIdPreviewRoute =
  AuthenticatedAssignmentsAssignmentIdPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => AuthenticatedAssignmentsAssignmentIdRoute,
  } as any)
const AuthenticatedClassesClassIdIndexRoute =
  AuthenticatedClassesClassIdIndexRouteImport.update({
    id: '/classes/$classId/',
    path: '/classes/$classId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassesClassIdGamesRoute =
  AuthenticatedClassesClassIdGamesRouteImport.update({
    id: '/classes/$classId/games',
    path: '/classes/$classId/games',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassesClassIdHomeworkRoute =
  AuthenticatedClassesClassIdHomeworkRouteImport.update({
    id: '/classes/$classId/homework',
    path: '/classes/$classId/homework',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassesClassIdMaterialsRoute =
  AuthenticatedClassesClassIdMaterialsRouteImport.update({
    id: '/classes/$classId/materials',
    path: '/classes/$classId/materials',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassesClassIdQuizzesRoute =
  AuthenticatedClassesClassIdQuizzesRouteImport.update({
    id: '/classes/$classId/quizzes',
    path: '/classes/$classId/quizzes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubmissionsAssignmentIdStudentIdRoute =
  AuthenticatedSubmissionsAssignmentIdStudentIdRouteImport.update({
    id: '/submissions/$assignmentId/$studentId',
    path: '/submissions/$assignmentId/$studentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/boss-question': typeof AuthenticatedBossQuestionRoute
  '/daily-double': typeof AuthenticatedDailyDoubleRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/vocab-bingo': typeof AuthenticatedVocabBingoRoute
  '/wager-round': typeof AuthenticatedWagerRoundRoute
  '/assignments/$assignmentId': typeof AuthenticatedAssignmentsAssignmentIdRouteWithChildren
  '/challenge/$matchId': typeof AuthenticatedChallengeMatchIdRoute
  '/present/$code': typeof AuthenticatedPresentCodeRoute
  '/quiz/$quizId': typeof AuthenticatedQuizQuizIdRoute
  '/oauth/google-drive/return': typeof OauthGoogleDriveReturnRoute
  '/assignments/$assignmentId/preview': typeof AuthenticatedAssignmentsAssignmentIdPreviewRoute
  '/classes/$classId/games': typeof AuthenticatedClassesClassIdGamesRoute
  '/classes/$classId/homework': typeof AuthenticatedClassesClassIdHomeworkRoute
  '/classes/$classId/materials': typeof AuthenticatedClassesClassIdMaterialsRoute
  '/classes/$classId/quizzes': typeof AuthenticatedClassesClassIdQuizzesRoute
  '/submissions/$assignmentId/$studentId': typeof AuthenticatedSubmissionsAssignmentIdStudentIdRoute
  '/assignments/$assignmentId/': typeof AuthenticatedAssignmentsAssignmentIdIndexRoute
  '/classes/$classId/': typeof AuthenticatedClassesClassIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/boss-question': typeof AuthenticatedBossQuestionRoute
  '/daily-double': typeof AuthenticatedDailyDoubleRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/vocab-bingo': typeof AuthenticatedVocabBingoRoute
  '/wager-round': typeof AuthenticatedWagerRoundRoute
  '/challenge/$matchId': typeof AuthenticatedChallengeMatchIdRoute
  '/present/$code': typeof AuthenticatedPresentCodeRoute
  '/quiz/$quizId': typeof AuthenticatedQuizQuizIdRoute
  '/oauth/google-drive/return': typeof OauthGoogleDriveReturnRoute
  '/assignments/$assignmentId/preview': typeof AuthenticatedAssignmentsAssignmentIdPreviewRoute
  '/classes/$classId/games': typeof AuthenticatedClassesClassIdGamesRoute
  '/classes/$classId/homework': typeof AuthenticatedClassesClassIdHomeworkRoute
  '/classes/$classId/materials': typeof AuthenticatedClassesClassIdMaterialsRoute
  '/classes/$classId/quizzes': typeof AuthenticatedClassesClassIdQuizzesRoute
  '/submissions/$assignmentId/$studentId': typeof AuthenticatedSubmissionsAssignmentIdStudentIdRoute
  '/assignments/$assignmentId': typeof AuthenticatedAssignmentsAssignmentIdIndexRoute
  '/classes/$classId': typeof AuthenticatedClassesClassIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/boss-question': typeof AuthenticatedBossQuestionRoute
  '/_authenticated/daily-double': typeof AuthenticatedDailyDoubleRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/vocab-bingo': typeof AuthenticatedVocabBingoRoute
  '/_authenticated/wager-round': typeof AuthenticatedWagerRoundRoute
  '/_authenticated/assignments/$assignmentId': typeof AuthenticatedAssignmentsAssignmentIdRouteWithChildren
  '/_authenticated/challenge/$matchId': typeof AuthenticatedChallengeMatchIdRoute
  '/_authenticated/present/$code': typeof AuthenticatedPresentCodeRoute
  '/_authenticated/quiz/$quizId': typeof AuthenticatedQuizQuizIdRoute
  '/oauth/google-drive/return': typeof OauthGoogleDriveReturnRoute
  '/_authenticated/assignments/$assignmentId/preview': typeof AuthenticatedAssignmentsAssignmentIdPreviewRoute
  '/_authenticated/classes/$classId/games': typeof AuthenticatedClassesClassIdGamesRoute
  '/_authenticated/classes/$classId/homework': typeof AuthenticatedClassesClassIdHomeworkRoute
  '/_authenticated/classes/$classId/materials': typeof AuthenticatedClassesClassIdMaterialsRoute
  '/_authenticated/classes/$classId/quizzes': typeof AuthenticatedClassesClassIdQuizzesRoute
  '/_authenticated/submissions/$assignmentId/$studentId': typeof AuthenticatedSubmissionsAssignmentIdStudentIdRoute
  '/_authenticated/assignments/$assignmentId/': typeof AuthenticatedAssignmentsAssignmentIdIndexRoute
  '/_authenticated/classes/$classId/': typeof AuthenticatedClassesClassIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/boss-question'
    | '/daily-double'
    | '/dashboard'
    | '/vocab-bingo'
    | '/wager-round'
    | '/assignments/$assignmentId'
    | '/challenge/$matchId'
    | '/present/$code'
    | '/quiz/$quizId'
    | '/oauth/google-drive/return'
    | '/assignments/$assignmentId/preview'
    | '/classes/$classId/games'
    | '/classes/$classId/homework'
    | '/classes/$classId/materials'
    | '/classes/$classId/quizzes'
    | '/submissions/$assignmentId/$studentId'
    | '/assignments/$assignmentId/'
    | '/classes/$classId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/boss-question'
    | '/daily-double'
    | '/dashboard'
    | '/vocab-bingo'
    | '/wager-round'
    | '/challenge/$matchId'
    | '/present/$code'
    | '/quiz/$quizId'
    | '/oauth/google-drive/return'
    | '/assignments/$assignmentId/preview'
    | '/classes/$classId/games'
    | '/classes/$classId/homework'
    | '/classes/$classId/materials'
    | '/classes/$classId/quizzes'
    | '/submissions/$assignmentId/$studentId'
    | '/assignments/$assignmentId'
    | '/classes/$classId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/boss-question'
    | '/_authenticated/daily-double'
    | '/_authenticated/dashboard'
    | '/_authenticated/vocab-bingo'
    | '/_authenticated/wager-round'
    | '/_authenticated/assignments/$assignmentId'
    | '/_authenticated/challenge/$matchId'
    | '/_authenticated/present/$code'
    | '/_authenticated/quiz/$quizId'
    | '/oauth/google-drive/return'
    | '/_authenticated/assignments/$assignmentId/preview'
    | '/_authenticated/classes/$classId/games'
    | '/_authenticated/classes/$classId/homework'
    | '/_authenticated/classes/$classId/materials'
    | '/_authenticated/classes/$classId/quizzes'
    | '/_authenticated/submissions/$assignmentId/$studentId'
    | '/_authenticated/assignments/$assignmentId/'
    | '/_authenticated/classes/$classId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  OauthGoogleDriveReturnRoute: typeof OauthGoogleDriveReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boss-question': {
      id: '/_authenticated/boss-question'
      path: '/boss-question'
      fullPath: '/boss-question'
      preLoaderRoute: typeof AuthenticatedBossQuestionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily-double': {
      id: '/_authenticated/daily-double'
      path: '/daily-double'
      fullPath: '/daily-double'
      preLoaderRoute: typeof AuthenticatedDailyDoubleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vocab-bingo': {
      id: '/_authenticated/vocab-bingo'
      path: '/vocab-bingo'
      fullPath: '/vocab-bingo'
      preLoaderRoute: typeof AuthenticatedVocabBingoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wager-round': {
      id: '/_authenticated/wager-round'
      path: '/wager-round'
      fullPath: '/wager-round'
      preLoaderRoute: typeof AuthenticatedWagerRoundRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assignments/$assignmentId': {
      id: '/_authenticated/assignments/$assignmentId'
      path: '/assignments/$assignmentId'
      fullPath: '/assignments/$assignmentId'
      preLoaderRoute: typeof AuthenticatedAssignmentsAssignmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/challenge/$matchId': {
      id: '/_authenticated/challenge/$matchId'
      path: '/challenge/$matchId'
      fullPath: '/challenge/$matchId'
      preLoaderRoute: typeof AuthenticatedChallengeMatchIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/present/$code': {
      id: '/_authenticated/present/$code'
      path: '/present/$code'
      fullPath: '/present/$code'
      preLoaderRoute: typeof AuthenticatedPresentCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quiz/$quizId': {
      id: '/_authenticated/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof AuthenticatedQuizQuizIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/oauth/google-drive/return': {
      id: '/oauth/google-drive/return'
      path: '/oauth/google-drive/return'
      fullPath: '/oauth/google-drive/return'
      preLoaderRoute: typeof OauthGoogleDriveReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assignments/$assignmentId/': {
      id: '/_authenticated/assignments/$assignmentId/'
      path: '/'
      fullPath: '/assignments/$assignmentId/'
      preLoaderRoute: typeof AuthenticatedAssignmentsAssignmentIdIndexRouteImport
      parentRoute: typeof AuthenticatedAssignmentsAssignmentIdRoute
    }
    '/_authenticated/assignments/$assignmentId/preview': {
      id: '/_authenticated/assignments/$assignmentId/preview'
      path: '/preview'
      fullPath: '/assignments/$assignmentId/preview'
      preLoaderRoute: typeof AuthenticatedAssignmentsAssignmentIdPreviewRouteImport
      parentRoute: typeof AuthenticatedAssignmentsAssignmentIdRoute
    }
    '/_authenticated/classes/$classId/': {
      id: '/_authenticated/classes/$classId/'
      path: '/classes/$classId'
      fullPath: '/classes/$classId/'
      preLoaderRoute: typeof AuthenticatedClassesClassIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes/$classId/games': {
      id: '/_authenticated/classes/$classId/games'
      path: '/classes/$classId/games'
      fullPath: '/classes/$classId/games'
      preLoaderRoute: typeof AuthenticatedClassesClassIdGamesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes/$classId/homework': {
      id: '/_authenticated/classes/$classId/homework'
      path: '/classes/$classId/homework'
      fullPath: '/classes/$classId/homework'
      preLoaderRoute: typeof AuthenticatedClassesClassIdHomeworkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes/$classId/materials': {
      id: '/_authenticated/classes/$classId/materials'
      path: '/classes/$classId/materials'
      fullPath: '/classes/$classId/materials'
      preLoaderRoute: typeof AuthenticatedClassesClassIdMaterialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes/$classId/quizzes': {
      id: '/_authenticated/classes/$classId/quizzes'
      path: '/classes/$classId/quizzes'
      fullPath: '/classes/$classId/quizzes'
      preLoaderRoute: typeof AuthenticatedClassesClassIdQuizzesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submissions/$assignmentId/$studentId': {
      id: '/_authenticated/submissions/$assignmentId/$studentId'
      path: '/submissions/$assignmentId/$studentId'
      fullPath: '/submissions/$assignmentId/$studentId'
      preLoaderRoute: typeof AuthenticatedSubmissionsAssignmentIdStudentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAssignmentsAssignmentIdRouteChildren {
  AuthenticatedAssignmentsAssignmentIdPreviewRoute: typeof AuthenticatedAssignmentsAssignmentIdPreviewRoute
  AuthenticatedAssignmentsAssignmentIdIndexRoute: typeof AuthenticatedAssignmentsAssignmentIdIndexRoute
}

const AuthenticatedAssignmentsAssignmentIdRouteChildren: AuthenticatedAssignmentsAssignmentIdRouteChildren =
  {
    AuthenticatedAssignmentsAssignmentIdPreviewRoute:
      AuthenticatedAssignmentsAssignmentIdPreviewRoute,
    AuthenticatedAssignmentsAssignmentIdIndexRoute:
      AuthenticatedAssignmentsAssignmentIdIndexRoute,
  }

const AuthenticatedAssignmentsAssignmentIdRouteWithChildren =
  AuthenticatedAssignmentsAssignmentIdRoute._addFileChildren(
    AuthenticatedAssignmentsAssignmentIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBossQuestionRoute: typeof AuthenticatedBossQuestionRoute
  AuthenticatedDailyDoubleRoute: typeof AuthenticatedDailyDoubleRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedVocabBingoRoute: typeof AuthenticatedVocabBingoRoute
  AuthenticatedWagerRoundRoute: typeof AuthenticatedWagerRoundRoute
  AuthenticatedAssignmentsAssignmentIdRoute: typeof AuthenticatedAssignmentsAssignmentIdRouteWithChildren
  AuthenticatedChallengeMatchIdRoute: typeof AuthenticatedChallengeMatchIdRoute
  AuthenticatedPresentCodeRoute: typeof AuthenticatedPresentCodeRoute
  AuthenticatedQuizQuizIdRoute: typeof AuthenticatedQuizQuizIdRoute
  AuthenticatedClassesClassIdGamesRoute: typeof AuthenticatedClassesClassIdGamesRoute
  AuthenticatedClassesClassIdHomeworkRoute: typeof AuthenticatedClassesClassIdHomeworkRoute
  AuthenticatedClassesClassIdMaterialsRoute: typeof AuthenticatedClassesClassIdMaterialsRoute
  AuthenticatedClassesClassIdQuizzesRoute: typeof AuthenticatedClassesClassIdQuizzesRoute
  AuthenticatedSubmissionsAssignmentIdStudentIdRoute: typeof AuthenticatedSubmissionsAssignmentIdStudentIdRoute
  AuthenticatedClassesClassIdIndexRoute: typeof AuthenticatedClassesClassIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBossQuestionRoute: AuthenticatedBossQuestionRoute,
  AuthenticatedDailyDoubleRoute: AuthenticatedDailyDoubleRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedVocabBingoRoute: AuthenticatedVocabBingoRoute,
  AuthenticatedWagerRoundRoute: AuthenticatedWagerRoundRoute,
  AuthenticatedAssignmentsAssignmentIdRoute:
    AuthenticatedAssignmentsAssignmentIdRouteWithChildren,
  AuthenticatedChallengeMatchIdRoute: AuthenticatedChallengeMatchIdRoute,
  AuthenticatedPresentCodeRoute: AuthenticatedPresentCodeRoute,
  AuthenticatedQuizQuizIdRoute: AuthenticatedQuizQuizIdRoute,
  AuthenticatedClassesClassIdGamesRoute: AuthenticatedClassesClassIdGamesRoute,
  AuthenticatedClassesClassIdHomeworkRoute:
    AuthenticatedClassesClassIdHomeworkRoute,
  AuthenticatedClassesClassIdMaterialsRoute:
    AuthenticatedClassesClassIdMaterialsRoute,
  AuthenticatedClassesClassIdQuizzesRoute:
    AuthenticatedClassesClassIdQuizzesRoute,
  AuthenticatedSubmissionsAssignmentIdStudentIdRoute:
    AuthenticatedSubmissionsAssignmentIdStudentIdRoute,
  AuthenticatedClassesClassIdIndexRoute: AuthenticatedClassesClassIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  OauthGoogleDriveReturnRoute: OauthGoogleDriveReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
