/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHomeworkRouteImport } from './routes/_authenticated/homework'
import { Route as AuthenticatedQuizzesRouteImport } from './routes/_authenticated/quizzes'
import { Route as AuthenticatedAssignmentsAssignmentIdRouteImport } from './routes/_authenticated/assignments.$assignmentId'
import { Route as AuthenticatedClassesClassIdRouteImport } from './routes/_authenticated/classes.$classId'
import { Route as AuthenticatedAssignmentsAssignmentIdIndexRouteImport } from './routes/_authenticated/assignments.$assignmentId.index'
import { Route as AuthenticatedAssignmentsAssignmentIdPreviewRouteImport } from './routes/_authenticated/assignments.$assignmentId.preview'
import { Route as AuthenticatedSubmissionsAssignmentIdStudentIdRouteImport } from './routes/_authenticated/submissions.$assignmentId.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeworkRoute = AuthenticatedHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuizzesRoute = AuthenticatedQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssignmentsAssignmentIdRoute =
  AuthenticatedAssignmentsAssignmentIdRouteImport.update({
    id: '/assignments/$assignmentId',
    path: '/assignments/$assignmentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassesClassIdRoute =
  AuthenticatedClassesClassIdRouteImport.update({
    id: '/classes/$classId',
    path: '/classes/$classId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssignmentsAssignmentIdIndexRoute =
  AuthenticatedAssignmentsAssignmentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAssignmentsAssignmentIdRoute,
  } as any)
const AuthenticatedAssignmentsAssignmentIdPreviewRoute =
  AuthenticatedAssignmentsAssignmentIdPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => AuthenticatedAssignmentsAssignmentIdRoute,
  } as any)
const AuthenticatedSubmissionsAssignmentIdStudentIdRoute =
  AuthenticatedSubmissionsAssignmentIdStudentIdRouteImport.update({
    id: '/submissions/$assignmentId/$studentId',
    path: '/submissions/$assignmentId/$studentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/homework': typeof AuthenticatedHomeworkRoute
  '/quizzes': typeof AuthenticatedQuizzesRoute
  '/assignments/$assignmentId': typeof AuthenticatedAssignmentsAssignmentIdRouteWithChildren
  '/classes/$classId': typeof AuthenticatedClassesClassIdRoute
  '/assignments/$assignmentId/preview': typeof AuthenticatedAssignmentsAssignmentIdPreviewRoute
  '/submissions/$assignmentId/$studentId': typeof AuthenticatedSubmissionsAssignmentIdStudentIdRoute
  '/assignments/$assignmentId/': typeof AuthenticatedAssignmentsAssignmentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/homework': typeof AuthenticatedHomeworkRoute
  '/quizzes': typeof AuthenticatedQuizzesRoute
  '/classes/$classId': typeof AuthenticatedClassesClassIdRoute
  '/assignments/$assignmentId/preview': typeof AuthenticatedAssignmentsAssignmentIdPreviewRoute
  '/submissions/$assignmentId/$studentId': typeof AuthenticatedSubmissionsAssignmentIdStudentIdRoute
  '/assignments/$assignmentId': typeof AuthenticatedAssignmentsAssignmentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/homework': typeof AuthenticatedHomeworkRoute
  '/_authenticated/quizzes': typeof AuthenticatedQuizzesRoute
  '/_authenticated/assignments/$assignmentId': typeof AuthenticatedAssignmentsAssignmentIdRouteWithChildren
  '/_authenticated/classes/$classId': typeof AuthenticatedClassesClassIdRoute
  '/_authenticated/assignments/$assignmentId/preview': typeof AuthenticatedAssignmentsAssignmentIdPreviewRoute
  '/_authenticated/submissions/$assignmentId/$studentId': typeof AuthenticatedSubmissionsAssignmentIdStudentIdRoute
  '/_authenticated/assignments/$assignmentId/': typeof AuthenticatedAssignmentsAssignmentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/homework'
    | '/quizzes'
    | '/assignments/$assignmentId'
    | '/classes/$classId'
    | '/assignments/$assignmentId/preview'
    | '/submissions/$assignmentId/$studentId'
    | '/assignments/$assignmentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/homework'
    | '/quizzes'
    | '/classes/$classId'
    | '/assignments/$assignmentId/preview'
    | '/submissions/$assignmentId/$studentId'
    | '/assignments/$assignmentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/homework'
    | '/_authenticated/quizzes'
    | '/_authenticated/assignments/$assignmentId'
    | '/_authenticated/classes/$classId'
    | '/_authenticated/assignments/$assignmentId/preview'
    | '/_authenticated/submissions/$assignmentId/$studentId'
    | '/_authenticated/assignments/$assignmentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/homework': {
      id: '/_authenticated/homework'
      path: '/homework'
      fullPath: '/homework'
      preLoaderRoute: typeof AuthenticatedHomeworkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quizzes': {
      id: '/_authenticated/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof AuthenticatedQuizzesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assignments/$assignmentId': {
      id: '/_authenticated/assignments/$assignmentId'
      path: '/assignments/$assignmentId'
      fullPath: '/assignments/$assignmentId'
      preLoaderRoute: typeof AuthenticatedAssignmentsAssignmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes/$classId': {
      id: '/_authenticated/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/classes/$classId'
      preLoaderRoute: typeof AuthenticatedClassesClassIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assignments/$assignmentId/': {
      id: '/_authenticated/assignments/$assignmentId/'
      path: '/'
      fullPath: '/assignments/$assignmentId/'
      preLoaderRoute: typeof AuthenticatedAssignmentsAssignmentIdIndexRouteImport
      parentRoute: typeof AuthenticatedAssignmentsAssignmentIdRoute
    }
    '/_authenticated/assignments/$assignmentId/preview': {
      id: '/_authenticated/assignments/$assignmentId/preview'
      path: '/preview'
      fullPath: '/assignments/$assignmentId/preview'
      preLoaderRoute: typeof AuthenticatedAssignmentsAssignmentIdPreviewRouteImport
      parentRoute: typeof AuthenticatedAssignmentsAssignmentIdRoute
    }
    '/_authenticated/submissions/$assignmentId/$studentId': {
      id: '/_authenticated/submissions/$assignmentId/$studentId'
      path: '/submissions/$assignmentId/$studentId'
      fullPath: '/submissions/$assignmentId/$studentId'
      preLoaderRoute: typeof AuthenticatedSubmissionsAssignmentIdStudentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAssignmentsAssignmentIdRouteChildren {
  AuthenticatedAssignmentsAssignmentIdPreviewRoute: typeof AuthenticatedAssignmentsAssignmentIdPreviewRoute
  AuthenticatedAssignmentsAssignmentIdIndexRoute: typeof AuthenticatedAssignmentsAssignmentIdIndexRoute
}

const AuthenticatedAssignmentsAssignmentIdRouteChildren: AuthenticatedAssignmentsAssignmentIdRouteChildren =
  {
    AuthenticatedAssignmentsAssignmentIdPreviewRoute:
      AuthenticatedAssignmentsAssignmentIdPreviewRoute,
    AuthenticatedAssignmentsAssignmentIdIndexRoute:
      AuthenticatedAssignmentsAssignmentIdIndexRoute,
  }

const AuthenticatedAssignmentsAssignmentIdRouteWithChildren =
  AuthenticatedAssignmentsAssignmentIdRoute._addFileChildren(
    AuthenticatedAssignmentsAssignmentIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHomeworkRoute: typeof AuthenticatedHomeworkRoute
  AuthenticatedQuizzesRoute: typeof AuthenticatedQuizzesRoute
  AuthenticatedAssignmentsAssignmentIdRoute: typeof AuthenticatedAssignmentsAssignmentIdRouteWithChildren
  AuthenticatedClassesClassIdRoute: typeof AuthenticatedClassesClassIdRoute
  AuthenticatedSubmissionsAssignmentIdStudentIdRoute: typeof AuthenticatedSubmissionsAssignmentIdStudentIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHomeworkRoute: AuthenticatedHomeworkRoute,
  AuthenticatedQuizzesRoute: AuthenticatedQuizzesRoute,
  AuthenticatedAssignmentsAssignmentIdRoute:
    AuthenticatedAssignmentsAssignmentIdRouteWithChildren,
  AuthenticatedClassesClassIdRoute: AuthenticatedClassesClassIdRoute,
  AuthenticatedSubmissionsAssignmentIdStudentIdRoute:
    AuthenticatedSubmissionsAssignmentIdStudentIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
